using System;

/*
 * Xamarin Shell Autogenerated Class
 */

namespace TicketingAppProject.Models
{
    public class Item
    {
        public string Id { get; set; }
        public string Text { get; set; }
        public string Description { get; set; }
    }
}